### PR TITLE
Run db migrations.

### PR DESCRIPTION
**Pull request by orhtej2**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by orhtej2** [comment]
!testme

**Comment by ericgaspar** [comment]
great! thanks for your help.
we may need `email=$(ynh_user_get_info --username=$admin --key=mail)` in the upgrade script

**Comment by orhtej2** [comment]
Problem is this is not valid e-mail, it should be `castopod@domain.tld` (otherwise user `castopod` will try to impersonate admin and get rejected by `dovecot`), but I see it's not working anyways (no mail is sent) - probably infamous TLS validation error I see no way of circumventing ([CodeIgniter's Email](https://codeigniter.com/user_guide/libraries/email.html) lacks necessary switches x_x).

**Comment by orhtej2** [comment]
Also-also when upgrading from 1.1.2 (current master) `admin` is not set - needs patching in `update` as well.

**Comment by ericgaspar** [comment]
I have merged your fix into testing: https://ci-apps-dev.yunohost.org/ci/job/10509

**Pull request closed without merging**
