### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
Why do it work only in private mode 🤔

**Comment by alexAubin** [comment]
The fact that it works in private mode is related to the fact that it returns error 500 (which the CI interprets as "the app doesn't return 200, hence it seems to be private", but it's more like a bug of the CI rather than the install being succesful)

The actual issue is that curling the app returns a miserable 500, but the log don't seem to contain any obvious error :/ Soooo I guess the way to debug this would be to actually install it and hope that `journalctl` on the proper php-fpm service shows sometimes more interesting

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
```
mysqli_sql_exception #1146
Table 'castopod.cp_settings' doesn't exist 
```
The problem is with the database apparently. I am cluless with what is going on. (I have installed a second time and got `Table 'castopod.cp_podcasts' doesn't exist`... 

@benjaminbellamy any idea on this issue?

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by kamazeuci** [comment]
oops. that's bad. (I am having issues with federation because apparently castopod 1.1.2~ynh2 is not compatible with Mastodon Secure Mode (AUTHORIZED_FETCH), so I hope this gets merged into master soon. thanks for your amazing work guys!!

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
`"code": 500, "message": "Table 'castopod.cp_podcasts' doesn't exist"`

Meh i don't know much about that app, but naively that sounds like the MySQL DB was not properly initialized x_x

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
