### PR TITLE
Redis

### PR DESCRIPTION
**Pull request by ericgaspar**
- Add Redis server

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by benjaminbellamy** [comment]
NB: The Redis database should not be shared: two instances of castopod should have a different redis database number (`cache.redis.database`).

**Comment by ericgaspar** [comment]
> NB: The Redis database should not be shared: two instances of castopod should have a different redis database number (`cache.redis.database`).

https://github.com/YunoHost-Apps/castopod_ynh/blob/881c4239559cd646c2001aa9006258dfaa491bfd/scripts/install#L114

I still need to find a better solution than having a 1/16 chance of picking the same number

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
Ok... it appears that we have an helper to grab the instance number...
https://github.com/YunoHost-Apps/castopod_ynh/blob/8076bec7d1f2f4f75b17c04966094c7189528743/scripts/install#L114

**Pull request merged**
