### PR TITLE
Version 1.6.5 take 2

### PR DESCRIPTION
**Pull request by orhtej2**
## Problem

- Version 1.6.5 unusable

## Solution

- Fix upgrade from 1.1.2
- Adjust config to properly serve 1.6.5 with `$data_dir`

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by orhtej2** [comment]
!testme !bookwormtestme

**Comment by orhtej2** [comment]
Oh FFS ┻━┻︵ \(°□°)/ ︵ ┻━┻

**Comment by orhtej2** [comment]
!testme

**Comment by orhtej2** [comment]
!testme

**Comment by orhtej2** [comment]
!testme

**Comment by ericgaspar** [comment]
@orhtej2 I'll let you manage the merge (I added you as package maintainer)

**Comment by orhtej2** [comment]
@ericgaspar thanks, I'll still wait for feedback in #101

**Comment by orhtej2** [comment]
!testme

**Pull request merged**
