### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to version alpha 53

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
(Restarting the test to try to gather more info, c.f. https://github.com/YunoHost/package_check/commit/f8f48a7e7f9f421911dbddeb8aaf9d58a00fd4f6 )

**Comment by ericgaspar** [comment]
From what I understand  (thanks @benjaminbellamy for the explanations)

The app, after install, displays a 500 error page: that seems to be the expected behavior.

The CI fails tests because of error 500 :/

The app needs a post-install action -> `/cp-install` (`.env` config file as already database fields set, so we only need to finish install process with 4/4 page).

I can see two possible solutions

**From castopod_ynh**
- Try to avoid post-install 4/4 page step (set `admin`, `password`, `email`, on `manifest.json` and achieve the [post-install with cURL](https://github.com/YunoHost-Apps/castopod_ynh/blob/7fe97ee09bf7a944d993b7a844d1d07a5171d171/scripts/install#L112-L129)
-> This doesn’t work yet… Not very used to this helper and I may have missed something o_O

**From upstream app**
- Instead of displaying a 500 error page, the app could redirect directly to whatever wizard page is needed to finish post-install.

**Comment by ericgaspar** [comment]
!testme

**Comment by ImaCrea** [comment]
fingers crossed 🤞(infinite thanks to you @ericgaspar can't wait to update our instance here 💎💎)

**Comment by ImaCrea** [comment]
J'ai tenté de mettre à jour à partir de la branche testing.
Malgré que l'upgrade semble s'être bien passée, de l'autre côté Castopod semble moins content :
Capture d’écran 2021-04-24 à 13 15 19

:/ Je vais tenter d'investiguer et remonter ici d'éventuelles précisions.

**Comment by ImaCrea** [comment]
C'est étrange ça semble marcher côté cp-admin mais certaines url renvoient vers une page d'erreur.. hm

**Comment by ImaCrea** [comment]
fyi -> https://code.podlibre.org/podlibre/castopod-host/-/issues/115

**Comment by ImaCrea** [comment]
> fyi -> https://code.podlibre.org/podlibre/castopod-host/-/issues/115

For your info, I couldn't update easily. Yassine from Castopod's team shared a few hints to make it work, it's all documented in their repo.

On my side, we were ok to restart from zero at this point (lucky we are!) so I installed a fresh clean install from this branch. It seems to run smoothly! Thank you for your precious contribution @ericgaspar :) Hopefully next updates will be smoother 🤞

**Pull request merged**
